### ISSUE TITLE
[BUG] Inserting some polish characters to database fails (probably not only polish) 

### ISSUE THREAD

**Issue by bambalooon** [denzilferreira/aware-client#6]
As I pointed out in title - when you try to synchronize local Aware DB with some polish characters ('ę' for sure) - nothing happens, you don't get any failure - response status code is 200(OK).
Other polish characters (like 'ł' for example) are replaced with question mark ('?').
I think Aware should correctly replicate characters from every language.

It would be also nice to change database default charset to utf8 from latin1_swedish_ci which can generate some additional issues.

**Comment by denzilferreira** [comment]
This should be solved now. The default charset has been set to utf8 system-wide. However, if you are hosting your database, it should use your database’s default charset.

Cheers,
Denzil

**Comment by bambalooon** [comment]
Thanks for quick response.
After Your fix I no longer get failure on synchronization, but unfortunately polish characters are still replaced (and not only polish).

For example characters: 'ę', 'ł', 'ż', 'ś' are replaced with '?' and characters 'ó', '&#189;' are removed from text.

**Comment by denzilferreira** [comment]
OK, made some more configuration changes on how we handle the encoding. 
Try again and let us know if it's fixed. Thanks for helping us improve 
AWARE :) Really appreciate it!

**Comment by bambalooon** [comment]
It's still the same. Polish characters doesn't work.
And I'm glad You are this active in fixing bug that is stopping my progress.

**Comment by denzilferreira** [comment]
OK, try now. Hopefully this should be solved now.

**Comment by bambalooon** [comment]
Unfortunately - no changes.

**Comment by denzilferreira** [comment]
This is solved in mysql configuration, where the default encoding is set.
